### ISSUE TITLE
something about lidar_camera_calibration

### ISSUE THREAD

**Issue by GaHooooo** [HesaiTechnology/HesaiLidar-ros#11]
大佬您好，我从 https://github.com/ankitdhall/lidar_camera_calibration/pull/96  跳转过来的，我有一个pandar40p的驱动但是不能直接使用lidar_camera_calibration这个包，那个issue说您这个包能够使pandar40p适用于lidar_camera_calibration( https://github.com/ankitdhall )这个包，请问具体是怎么使用呢。

我首先试了下修改launch中p40p.launch的<arg name="server_ip" default="xxx"/>，但是	<arg name="pcap_file"  default=""/>我不知道填什么。
然后把config中的correction.csv替换为我原本pandar40p驱动中的矫正值
但是我launch之后会报错，跪求大佬解答，谢谢大佬

![image](https://user-images.githubusercontent.com/50771851/64439652-07f04180-d0fd-11e9-9edc-dd10efa4b9c6.png)

**Comment by GaHooooo** [comment]
emmmmm，突然间要素察觉，好像找错地方了

**Comment by FZUChenhaoLin** [comment]
您好，我也是這個問題，大哥解決了嗎？

**Comment by yangfanFred** [comment]
Hi Friends,

Currently we don't have resources to support related third party ROS projects.
But regarding to your issue of using this ROS driver: if you are using Pandar40P, please use our  newly updated General ROS: https://github.com/HesaiTechnology/HesaiLidar_General_ROS
About correction file, if Lidar is connected, ROS driver will read it from Lidar internal memory, you don't have to change the default setting.

Thanks,
