### ISSUE TITLE
GPS time sync

### ISSUE THREAD

**Issue by 306327680** [HesaiTechnology/HesaiLidar-ros#13]
hello
when I use the GPS PPS and GPRMC, in the ROS message there is a channel called "timestemp" and it shows 99999999, how could I the timestamp of each point when I connect the GPS PPS signal?

**Comment by 306327680** [comment]
![947687661](https://user-images.githubusercontent.com/22684364/66739395-276c4e00-eea3-11e9-9654-2c5a38acee62.jpg)
![1380503271](https://user-images.githubusercontent.com/22684364/66739400-29361180-eea3-11e9-9398-d479635d715b.jpg)

**Comment by trickyMan** [comment]
The points of this ROS published include timestamp.
https://github.com/HesaiTechnology/HesaiLidarSDK/blob/a5bfd5c51f09c676b747a260bd1622d76e2ca309/include/point_types.h#L11
