### ISSUE TITLE
launch文件中laser_return_type问题

### ISSUE THREAD

**Issue by TheGreatGalaxy** [HesaiTechnology/HesaiLidar-ros#14]

**Comment by TheGreatGalaxy** [comment]
在launch文件中看到40.launch和40P.launch的区别主要在于laser_return_type值分别为0和1，但是驱动中好像表示的是值雷达回波的模式，这个最终传递会给rawdata和input。
问题：
1.40和40p雷达与回波模式绑定了？40只能是单回波，而40p是双回波？对于驱动来说，解析数据与回波模式相关性在哪里？
2.40p的launch文件，解析不了40p雷达的数据包啊

**Comment by yangfanFred** [comment]
Hi TheGreatGalaxy,

1. The return mode is not fixed, both Pandar40 and Pandar40P support dual return the return type in launch file is only a default setting, you should set this parameter according to your configuration of Lidar you are using. Data will be doubled when using dual return mode compare to single return mode.

2. Parameters in launch file should be modified according to your configuration of Lidar and reading pcap file offline is not fully supported by our ROS driver currently.

Thanks
