### ISSUE TITLE
Wrong launch file for p40

### ISSUE THREAD

**Issue by zhrzhang** [HesaiTechnology/HesaiLidar-ros#16]
The `.launch` file ROS package for p40 seems to be the wrong one and `p40p.launch` file worked for my p40 LiDAR. Would you please look into it?

**Comment by yangfanFred** [comment]
Hello zhrzhang,

Do you mean the launch file in HesaiLidar-ROS project for p40? 
The ip and port parameters in launch files need to be configured by user according to their own settings when using our Lidar. 
While we do realized that it will be much easier for our new customers if default parameters in launch file work with default settings of Lidar directly. We will have an update on this very soon.
Thanks a lot for your contribute :)


> The `.launch` file ROS package for p40 seems to be the wrong one and `p40p.launch` file worked for my p40 LiDAR. Would you please look into it?

**Comment by yangfanFred** [comment]
We've updated the launch file to make it work directly with default settings of Lidar

**Comment by zhrzhang** [comment]
I think I had changed the port number in p40.launch, but I'll definitely try out the updated launch file. Thanks.

**Comment by zhrzhang** [comment]
The new launch file still doesn't work for me. It prints multiple lines of 
`packet size mismatch!` 
and the process died. After changing the `laser_return_type` into 0 (which is exactly the same with `p40p.launch`), the launch file worked.
