### ISSUE TITLE
About Timestamp

### ISSUE THREAD

**Issue by Ckerrr** [HesaiTechnology/HesaiLidar-ros#4]
I found that the Hesai driver publishes messages with the timestamps starting from the moment when launching the node.

I would suggest using the system clock time as the timestamp. It's more popular and easier to do other tasks, such as synchronization. deep fusion, etc.

Do you think it's a good idea?

**Comment by trickyMan** [comment]
It's ok for general purpose. But it's not ok if you want to get more precious timestamp, which is using to synchrolize with other sensor, such as IMU and other LiDAR.

**Comment by xiaoliangabc** [comment]
> It's ok for general purpose. But it's not ok if you want to get more precious timestamp, which is using to synchrolize with other sensor, such as IMU and other LiDAR.

Hello, how cain i get the timestamp from system clock？
