### ISSUE TITLE
How to Rotate the Frame/Coordinate/Axies

### ISSUE THREAD

**Issue by Ckerrr** [HesaiTechnology/HesaiLidar-ros#5]
For Hesai P40 Lidar, the y axis is aligned with the cable, but I think the cable facing backwards should be best. 

May I know how can I rotate the point cloud by 90 degrees when we launch p40p.launch?

I tried:
1. Configure in web control for the unit: "sync angle", "starting range" and "end range". Both not working.
2. Set the parameter in launch file: "start_angle". Not working.

Please help asap. Appreciate it very much!

**Comment by Ckerrr** [comment]
Thanks a lot.

**Comment by stan-guer** [comment]
Similar issue here.
