### ISSUE TITLE
pcap解析为pcd

### ISSUE THREAD

**Issue by ywfwyht** [HesaiTechnology/HesaiLidar-ros#9]
您好，请问pcap可以解析成单帧pcd点云吗？

**Comment by trickyMan** [comment]
可以啊。这个项目里面是有SDK的，callback的数据结构就是pcl::pointcloud, 你可以保存下来的。你看看代码？

https://github.com/HesaiTechnology/HesaiLidarSDK/blob/d9d5b9a94b74e2c4925311b487cc260d3ceebb3e/sample/pandar40p/pandar40p.cc#L8

**Comment by ywfwyht** [comment]
好的，谢谢，我先看看。

**Comment by Caicaiyoko** [comment]
请问，支持pander64么，pacp解析为pcd,ply之类的，我看这两个链接都include pander40，我不是特别懂C++...

**Comment by trickyMan** [comment]
Pandar64不支持哈

**Comment by Caicaiyoko** [comment]
> Pandar64不支持哈

谢谢回复，还想请教一个问题，如果想实时的接受雷达数据并做目标检测，那该如何提取雷达的pacp数据呢，我看源码是以paraview为核心，转成vtk再读出？64的ros支持pcl实时导出，但pcd不得行？

**Comment by trickyMan** [comment]
两个手段：
1. pcl 可以存为PCD的。
2. 另外，如果是pcap的话，有两个方案，第一个方案是用pcapreplay ，把pcap按照原有的顺序用udp发出来，模拟一台真实的lidar，同时使用ROS/SDK接收 or 进行转换就可以了，第二个方案是写c++程序读取pcap里面的内容，一个包一个包读出来，参考SDK/ROS对数据包的解析，同样可以得到pcl/pcd

**Comment by cwp2333** [comment]
我这边有一个rosbag的包是pandar40的然后里面的点云数据是无序的 请问我应该怎么知道哪些是xyz

**Comment by yangfanFred** [comment]
用rostopic echo显示msg，msg头部包含了数据结构定义
